// *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***


export const Region = {
    Here: "HERE",
    OverThere: "OVER_THERE",
} as const;

export type Region = (typeof Region)[keyof typeof Region];
