// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.xyz.outputs;

import com.pulumi.core.annotations.CustomType;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;

@CustomType
public final class GetDataSourceResult {
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    private String id;
    private String sampleAttribute;

    private GetDataSourceResult() {}
    /**
     * @return The provider-assigned unique ID for this managed resource.
     * 
     */
    public String id() {
        return this.id;
    }
    public String sampleAttribute() {
        return this.sampleAttribute;
    }

    public static Builder builder() {
        return new Builder();
    }

    public static Builder builder(GetDataSourceResult defaults) {
        return new Builder(defaults);
    }
    @CustomType.Builder
    public static final class Builder {
        private String id;
        private String sampleAttribute;
        public Builder() {}
        public Builder(GetDataSourceResult defaults) {
    	      Objects.requireNonNull(defaults);
    	      this.id = defaults.id;
    	      this.sampleAttribute = defaults.sampleAttribute;
        }

        @CustomType.Setter
        public Builder id(String id) {
            if (id == null) {
              throw new MissingRequiredPropertyException("GetDataSourceResult", "id");
            }
            this.id = id;
            return this;
        }
        @CustomType.Setter
        public Builder sampleAttribute(String sampleAttribute) {
            if (sampleAttribute == null) {
              throw new MissingRequiredPropertyException("GetDataSourceResult", "sampleAttribute");
            }
            this.sampleAttribute = sampleAttribute;
            return this;
        }
        public GetDataSourceResult build() {
            final var _resultValue = new GetDataSourceResult();
            _resultValue.id = id;
            _resultValue.sampleAttribute = sampleAttribute;
            return _resultValue;
        }
    }
}
