// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.xyz;

import com.pulumi.core.Output;
import com.pulumi.core.annotations.Import;
import com.pulumi.xyz.region.enums.Region;
import java.util.Objects;
import java.util.Optional;
import javax.annotation.Nullable;


public final class ProviderArgs extends com.pulumi.resources.ResourceArgs {

    public static final ProviderArgs Empty = new ProviderArgs();

    /**
     * A region which should be used.
     * 
     */
    @Import(name="region", json=true)
    private @Nullable Output<Region> region;

    /**
     * @return A region which should be used.
     * 
     */
    public Optional<Output<Region>> region() {
        return Optional.ofNullable(this.region);
    }

    private ProviderArgs() {}

    private ProviderArgs(ProviderArgs $) {
        this.region = $.region;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(ProviderArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private ProviderArgs $;

        public Builder() {
            $ = new ProviderArgs();
        }

        public Builder(ProviderArgs defaults) {
            $ = new ProviderArgs(Objects.requireNonNull(defaults));
        }

        /**
         * @param region A region which should be used.
         * 
         * @return builder
         * 
         */
        public Builder region(@Nullable Output<Region> region) {
            $.region = region;
            return this;
        }

        /**
         * @param region A region which should be used.
         * 
         * @return builder
         * 
         */
        public Builder region(Region region) {
            return region(Output.of(region));
        }

        public ProviderArgs build() {
            return $;
        }
    }

}
