// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.xyz;

import com.pulumi.core.Output;
import com.pulumi.core.TypeShape;
import com.pulumi.deployment.Deployment;
import com.pulumi.deployment.InvokeOptions;
import com.pulumi.deployment.InvokeOutputOptions;
import com.pulumi.xyz.Utilities;
import com.pulumi.xyz.inputs.GetDataSourceArgs;
import com.pulumi.xyz.inputs.GetDataSourcePlainArgs;
import com.pulumi.xyz.outputs.GetDataSourceResult;
import java.util.concurrent.CompletableFuture;

public final class XyzFunctions {
    public static Output<GetDataSourceResult> getDataSource(GetDataSourceArgs args) {
        return getDataSource(args, InvokeOptions.Empty);
    }
    public static CompletableFuture<GetDataSourceResult> getDataSourcePlain(GetDataSourcePlainArgs args) {
        return getDataSourcePlain(args, InvokeOptions.Empty);
    }
    public static Output<GetDataSourceResult> getDataSource(GetDataSourceArgs args, InvokeOptions options) {
        return Deployment.getInstance().invoke("xyz:index/getDataSource:getDataSource", TypeShape.of(GetDataSourceResult.class), args, Utilities.withVersion(options));
    }
    public static Output<GetDataSourceResult> getDataSource(GetDataSourceArgs args, InvokeOutputOptions options) {
        return Deployment.getInstance().invoke("xyz:index/getDataSource:getDataSource", TypeShape.of(GetDataSourceResult.class), args, Utilities.withVersion(options));
    }
    public static CompletableFuture<GetDataSourceResult> getDataSourcePlain(GetDataSourcePlainArgs args, InvokeOptions options) {
        return Deployment.getInstance().invokeAsync("xyz:index/getDataSource:getDataSource", TypeShape.of(GetDataSourceResult.class), args, Utilities.withVersion(options));
    }
}
