# coding=utf-8
# *** WARNING: this file was generated by the Pulumi Terraform Bridge (tfgen) Tool. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

import builtins
import builtins
from enum import Enum

__all__ = [
    'Region',
]


class Region(builtins.str, Enum):
    HERE = "HERE"
    OVER_THERE = "OVER_THERE"
