// *** WARNING: this file was generated by pulumi-java-gen. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

package com.pulumi.xyz.inputs;

import com.pulumi.core.annotations.Import;
import com.pulumi.exceptions.MissingRequiredPropertyException;
import java.lang.String;
import java.util.Objects;


public final class GetDataSourcePlainArgs extends com.pulumi.resources.InvokeArgs {

    public static final GetDataSourcePlainArgs Empty = new GetDataSourcePlainArgs();

    @Import(name="sampleAttribute", required=true)
    private String sampleAttribute;

    public String sampleAttribute() {
        return this.sampleAttribute;
    }

    private GetDataSourcePlainArgs() {}

    private GetDataSourcePlainArgs(GetDataSourcePlainArgs $) {
        this.sampleAttribute = $.sampleAttribute;
    }

    public static Builder builder() {
        return new Builder();
    }
    public static Builder builder(GetDataSourcePlainArgs defaults) {
        return new Builder(defaults);
    }

    public static final class Builder {
        private GetDataSourcePlainArgs $;

        public Builder() {
            $ = new GetDataSourcePlainArgs();
        }

        public Builder(GetDataSourcePlainArgs defaults) {
            $ = new GetDataSourcePlainArgs(Objects.requireNonNull(defaults));
        }

        public Builder sampleAttribute(String sampleAttribute) {
            $.sampleAttribute = sampleAttribute;
            return this;
        }

        public GetDataSourcePlainArgs build() {
            if ($.sampleAttribute == null) {
                throw new MissingRequiredPropertyException("GetDataSourcePlainArgs", "sampleAttribute");
            }
            return $;
        }
    }

}
