name: lint

on:
  workflow_call:
    inputs: {}
  pull_request:
    branches:
    - main
    - v*
    - feature*
    paths-ignore:
    - CHANGELOG.md

env:
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  lint:
    name: lint
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3
    - name: Install go
      uses: actions/setup-go@v4
      with:
        # The versions of golangci-lint and setup-go here cross-depend and need to update together.
        go-version: 1.21
        # Either this action or golangci-lint needs to disable the cache
        cache: false
    - name: disarm go:embed directives to enable lint
      continue-on-error: true # this fails if there are no go:embed directives
      run: |
        git grep -l 'go:embed' -- provider | xargs sed -i 's/go:embed/ goembed/g'
    - name: prepare upstream
      continue-on-error: true
      run: make upstream
    - run: cd provider && go mod tidy
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
      with:
        version: v1.54.1
        working-directory: provider
        skip-pkg-cache: true
